
package library_managment_system2;

import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.concurrent.TimeUnit;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import java.util.Calendar;
import java.util.GregorianCalendar;


/**
 *
 * @author Apeksha Kulkarni
 */
public class Event extends javax.swing.JFrame {

    ImageIcon a=new ImageIcon("D:\\My Project\\Library_managment_system_demo\\src\\library\\management\\system\\icons\\gift.gif");
    ImageIcon b=new ImageIcon("D:\\My Project\\Library_managment_system_demo\\src\\library\\management\\system\\icons\\Award.gif");
    ImageIcon c=new ImageIcon("D:\\My Project\\Library_managment_system_demo\\src\\library\\management\\system\\icons\\Celeb1.gif");
    ImageIcon d=new ImageIcon("D:\\My Project\\Library_managment_system_demo\\src\\library\\management\\system\\icons\\LibraryHoli.gif");
    ImageIcon e=new ImageIcon("D:\\My Project\\Library_managment_system_demo\\src\\library\\management\\system\\icons\\Oops2.png");
    ImageIcon f=new ImageIcon("D:\\My Project\\Library_managment_system_demo\\src\\library\\management\\system\\icons\\Librarian Day2.gif");
    ImageIcon g=new ImageIcon("D:\\My Project\\Library_managment_system_demo\\src\\library\\management\\system\\icons\\Library Month11.gif");
    ImageIcon h=new ImageIcon("D:\\My Project\\Library_managment_system_demo\\src\\library\\management\\system\\icons\\Book Day.gif");
    ImageIcon an=new ImageIcon("D:\\My Project\\Library_managment_system_demo\\src\\library\\management\\system\\icons\\Anniversary.gif");

    /**
     * Creates new form Event
     */
    public Event() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Calender1 = new com.toedter.calendar.JCalendar();
        Img = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt = new javax.swing.JTextField();
        lbl1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Calender1.setBackground(new java.awt.Color(255, 153, 153));
        Calender1.setBorder(new javax.swing.border.MatteBorder(null));
        Calender1.setDate(new java.util.Date(1650447537000L));
        Calender1.setDecorationBackgroundColor(new java.awt.Color(255, 153, 153));
        Calender1.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        Calender1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Calender1MouseEntered(evt);
            }
        });
        Calender1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                Calender1ComponentShown(evt);
            }
        });
        jPanel1.add(Calender1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 460, 510));

        Img.setBackground(new java.awt.Color(153, 255, 255));
        Img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Img.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 2, true));
        Img.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Img.setOpaque(true);
        jPanel1.add(Img, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, 270, 260));

        jButton1.setFont(new java.awt.Font("Bookman Old Style", 3, 22)); // NOI18N
        jButton1.setText("Check Event");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, 180, 70));

        txt.setFont(new java.awt.Font("Bookman Old Style", 1, 22)); // NOI18N
        jPanel1.add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, 180, 50));

        lbl1.setBackground(new java.awt.Color(255, 204, 204));
        lbl1.setFont(new java.awt.Font("Bookman Old Style", 3, 24)); // NOI18N
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        lbl1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl1.setOpaque(true);
        jPanel1.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 270, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 940, 590));

        jLabel1.setBackground(new java.awt.Color(204, 255, 153));
        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 3, 48)); // NOI18N
        jLabel1.setText("Events !!");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 230, 60));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/management/system/icons/GoBack.JPG"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/management/system/icons/IMG7.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 890));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Calender1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Calender1ComponentShown
//          JLabel l2 = new JLabel("");
//            l2.setVerticalAlignment(SwingConstants.TOP);
//            ImageIcon i1  = new ImageIcon(ClassLoader.getSystemResource("library/management/system/icons/second.png"));
//            Image i2 = i1.getImage().getScaledInstance(150, 150,Image.SCALE_DEFAULT);
//            ImageIcon i3 = new ImageIcon(i2);
//            l2 = new JLabel(i3);
//            l2.setBounds(60, 140, 159, 152);
//            contentPane.add(l2);
    }//GEN-LAST:event_Calender1ComponentShown

    private void Calender1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Calender1MouseEntered
        
    }//GEN-LAST:event_Calender1MouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
        //String date=Date1.
        //String calendar=dateformat.format()
        String calendar = dateformat.format(Calender1.getDate());
        //String date = dateformat.format(Date1.getDate());
        //txt.setText(date);
        txt.setText(calendar);
        
        if (txt.getText().equals("2022-05-01"))
        {
            Img.setIcon(g); 
            lbl1.setText("Library Month!");
        }
        else
        if (txt.getText().equals("2022-05-08"))
        {
            Img.setIcon(a); 
            lbl1.setText("Gift Distribution !!");
        }
        else
             if (txt.getText().equals("2022-05-12"))
        {
            Img.setIcon(b);
            lbl1.setText("Award Party !!");

        }
         else
             if (txt.getText().equals("2022-05-15"))
        {
            Img.setIcon(c); 
            lbl1.setText("Library Week !!");

        }
        else
             if (txt.getText().equals("2022-05-22"))
        {
            Img.setIcon(d); 
            lbl1.setText("Library Holiday !");
        }
        else
             if (txt.getText().equals("2022-05-26"))
        {
            Img.setIcon(f); 
            lbl1.setText("Librarian Day!");
        }
        else
       
             if (txt.getText().equals("2022-06-04"))
        {
            Img.setIcon(h); 
            lbl1.setText("Book Day!");
        }
        else
             if (txt.getText().equals("2022-06-12"))
        {
            Img.setIcon(an); 
            lbl1.setText("Library Anniversary!");
        }
        else
             {
               lbl1.setText("Oops!! No Events!");
               Img.setIcon(e);
             }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ////        this.setVisible(false);
        ////        new Home().setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Event().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar Calender1;
    private javax.swing.JLabel Img;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JTextField txt;
    // End of variables declaration//GEN-END:variables
}
