
package library_managment_system2;

import Tools.DatabaseConnectivity;
import javax.swing.JFrame;
import javax.swing.JTable;


/**
 *
 * @author Apeksha Kulkarni
 */
public class ReturnList extends javax.swing.JFrame {

    /**
     * Creates new form ReturnList
     */
    public ReturnList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ASCENDING = new javax.swing.JButton();
        DESCENDING = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_return = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ASCENDING.setBackground(new java.awt.Color(204, 255, 204));
        ASCENDING.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        ASCENDING.setText("ASC");
        ASCENDING.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ASCENDINGActionPerformed(evt);
            }
        });
        jPanel1.add(ASCENDING, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, 120, 60));

        DESCENDING.setBackground(new java.awt.Color(204, 255, 204));
        DESCENDING.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        DESCENDING.setText("DESC");
        DESCENDING.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DESCENDINGActionPerformed(evt);
            }
        });
        jPanel1.add(DESCENDING, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, 130, 60));

        table_return.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        table_return.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(table_return);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 1060, 390));

        jButton2.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 110, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 1170, 630));
        jPanel1.getAccessibleContext().setAccessibleName("");
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("Return List");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 230, 60));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/management/system/icons/GoBack.JPG"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 47));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/management/system/icons/IMGW1.jpeg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 1400, 830));

        setSize(new java.awt.Dimension(1411, 881));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Tools.Helper.setCenter(this);
        DatabaseConnectivity db = new DatabaseConnectivity();

        String[][] data = db.Select("SELECT * FROM loan");
        String[] title = {"Member Id", "Member Name", "ISBN Code", "Book Name", "Issued Date", "Return Date"};

        table_return = new JTable(data, title);
        jScrollPane3.setViewportView(table_return);
   
    }//GEN-LAST:event_formWindowOpened

    private void ASCENDINGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ASCENDINGActionPerformed
        // TODO add your handling code here:
        Tools.Helper.setCenter(this);
        DatabaseConnectivity db = new DatabaseConnectivity();
        
        String[][] data = db.Select("SELECT * FROM loan ORDER BY rno ASC");
        String[] title = {"Member Id", "Member Name", "ISBN Code", "Book Name", "Issued Date", "Return Date"};

        table_return = new JTable(data, title);
        jScrollPane3.setViewportView(table_return);
    }//GEN-LAST:event_ASCENDINGActionPerformed

    private void DESCENDINGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DESCENDINGActionPerformed
        // TODO add your handling code here:
         Tools.Helper.setCenter(this);
        DatabaseConnectivity db = new DatabaseConnectivity();
        
        String[][] data = db.Select("SELECT * FROM loan ORDER BY rno DESC");
        String[] title = {"Member Id", "Member Name", "ISBN Code", "Book Name", "Issued Date", "Return Date"};

        table_return = new JTable(data, title);
        jScrollPane3.setViewportView(table_return);
    }//GEN-LAST:event_DESCENDINGActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false); 
        //new Home().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DatabaseConnectivity db = new DatabaseConnectivity();

        String rno = table_return.getValueAt(table_return.getSelectedRow(), 0).toString();
        //String qry = "DELETE FROM book WHERE isbn = " + id;
        String qry ="DELETE FROM loan WHERE rno LIKE '" + rno + "'";
        boolean r = db.execute(qry);
        if (r) {
            formWindowOpened(null);
            Tools.Helper.show(this, "Deleted");
        } else {
            Tools.Helper.show(this, "opps, please try again!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ASCENDING;
    private javax.swing.JButton DESCENDING;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable table_return;
    // End of variables declaration//GEN-END:variables
}
